// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXWvznDBxFMyNLdX-Gapg9DNcT-ZHjnM',
    appId: '1:1092545038688:web:101908936a9950aafeb605',
    messagingSenderId: '1092545038688',
    projectId: 'kissandigitalapptest',
    authDomain: 'kissandigitalapptest.firebaseapp.com',
    storageBucket: 'kissandigitalapptest.firebasestorage.app',
    measurementId: 'G-PFDLM1M7TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB968CCHJDaHU3Kg5XzbpMsOmZPngcaSag',
    appId: '1:1092545038688:android:e4450c451a6f8a52feb605',
    messagingSenderId: '1092545038688',
    projectId: 'kissandigitalapptest',
    storageBucket: 'kissandigitalapptest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOoje6YJzD3hTVa87ktxrVxMngAmo2I-Q',
    appId: '1:1092545038688:ios:0c295541d04662b2feb605',
    messagingSenderId: '1092545038688',
    projectId: 'kissandigitalapptest',
    storageBucket: 'kissandigitalapptest.firebasestorage.app',
    iosBundleId: 'com.example.kissapDigitalAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOoje6YJzD3hTVa87ktxrVxMngAmo2I-Q',
    appId: '1:1092545038688:ios:0c295541d04662b2feb605',
    messagingSenderId: '1092545038688',
    projectId: 'kissandigitalapptest',
    storageBucket: 'kissandigitalapptest.firebasestorage.app',
    iosBundleId: 'com.example.kissapDigitalAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdXWvznDBxFMyNLdX-Gapg9DNcT-ZHjnM',
    appId: '1:1092545038688:web:026518d706ceb3fcfeb605',
    messagingSenderId: '1092545038688',
    projectId: 'kissandigitalapptest',
    authDomain: 'kissandigitalapptest.firebaseapp.com',
    storageBucket: 'kissandigitalapptest.firebasestorage.app',
    measurementId: 'G-F6G4KV6E9M',
  );
}
